services:
  app:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lucazsilverio/tdd
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - app-php
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-php

networks:
  app-php:
    driver: bridge